fixed indentation

diff --git a/.github/workflows/01-building-blocks-relearning.yaml b/.github/workflows/01-building-blocks-relearning.yaml
--- a/.github/workflows/01-building-blocks-relearning.yaml
+++ b/.github/workflows/01-building-blocks-relearning.yaml
@@ -9,13 +9,13 @@ jobs:
     first-job:
         runs-on: ubuntu-latest
         steps:
-            - name: Say hello
-              run: echo "Hello, World!"
-            - name: Failed Step
-              run: |
-                echo "I will fail"
-                exit 1
-            - name: Say Goodbye
-              run: echo "Goodbye"  
+             - name: Say hello
+               run: echo "Hello, World!"
+             - name: Failed Step
+               run: |
+                  echo "I will fail"
+                  exit 1
+             - name: Say Goodbye
+               run: echo "Goodbye"  
 
             
