test failure

diff --git a/.github/workflows/01-building-blocks-relearning.yaml b/.github/workflows/01-building-blocks-relearning.yaml
--- a/.github/workflows/01-building-blocks-relearning.yaml
+++ b/.github/workflows/01-building-blocks-relearning.yaml
@@ -11,6 +11,11 @@ jobs:
         steps:
             - name: Say hello
               run: echo "Hello, World!"
+            - name: Failed Step
+              run: |
+                echo "I will fail"
+                exit 1
             - name: Say Goodbye
-              run: echo "Goodbye"   
+              run: echo "Goodbye"  
+
             
